package.json
pnpm 이외의 패키지 매니저로 패키지를 설치 및 추가하는 것을 막고자 강제 스크립트를 추가했어요.
- pnpm 강제하기 스크립트 추가
When you use pnpm on a project, you don't want others to accidentally run `npm install` or `yarn`. To prevent devs from using other package managers, you can add the following `preinstall` script to your `package.json`:
```bash
{
"scripts": {
"preinstall": "npx only-allow pnpm"
}
}
```
Now, whenever someone runs `npm install` or `yarn`, they'll get an error instead and installation will not proceed.
=> [⚙️ chore] pnpm 설치 강제하기 (#9)

src/stories/Page.tsx
vercel에서 빌드 시 발생하는 quot 오류를 수정했어요.
- prettier 가독성 증대
- `"` → `&quot;` 변경
이는 HTML 엔티티 인코딩과 관련이 있어요. 
1. HTML 컨텍스트에서 충돌
HTML에서 따옴표(`"`)는 속성값을 구분하는 데 사용돼요. 문자열 내의 따옴표가 HTML 구문 분석을 방해할 수 있어요.
2. XML 파싱 이슈
JSX나 XML 기반 템플릿에서 문자열 내의 따옴표가 마크업 구조와 충돌할 수 있어요. 
3. 보안 문제
이스케이프 처리되지 않은 따옴표는 XSS(Cross-Site Scripting) 공격에 악용될 수 있어요.
=> [🔧 fix] 빌드 시 발생하는 quot 오류 수정 (#18)

.storybook/preview.ts, lefthook.yml, public/mockServiceWorker.js, src/constants/index.ts, src/stories/Button.tsx, src/stories/Header.tsx
lefthook.yml prettier 명령어의 glob에서 정의한 확장자들 사이에 있던 공백을 제거하여 해당 확장자들의 파일에 적용됨을 명시하고 현재 디렉토리 뿐만 아니라 하위 디렉토리의 파일들도 적용되도록 수정했어요
적용되어야했던 파일들의 코드를 포맷팅했어요
- lefthook.yml prettier 명령어의 타겟 확장자 사이에 있던 공백 제거
- 하위 디렉토리의 파일들도 prettier가 적용되도록 수정
- 모든 파일들의 코드 포맷팅
=> [🔧 fix] lefthook.yml의 prettier 명령어에 적용될 확장자 사이의 공백을 제거하고 모든 파일의 코드 포맷팅

src/app/layout.tsx, src/components/common/button/MoreViewButton.tsx, src/components/common/index.ts, src/components/layout/footer/Footer.tsx, src/components/layout/header/Header.tsx, src/stories/button/Button.stories.ts
상품에 있는 '더 보기' 버튼을 제작했어요.
- '더 보기' 버튼을 추가했어요.
- 스토리북에도 추가로 작성했어요.
- 레이아웃 너비값을 임시로 픽셀로 지정했어요. 
피그마에 정의된 `outline` variant는 필요 없다고 하셔서 한 가지 베리언트만 사용했습니다 ~
=> [✨ feat] 상품 더 보기 컴포넌트 제작 (#65)

src/app/layout.tsx, src/components/common/button/Button.tsx, src/components/common/button/ScrollToTopButton.tsx, src/components/common/index.ts, src/stories/button/Button.stories.ts, src/styles/globals.css
위로 가기 버튼을 추가했어요. 
- 버튼 컴포넌트에 `transition`, `duration`을 추가했어요.
- 위로 가기 버튼을 제작했어요.
- 300px이상 스크롤 시 위로 가기 버튼이 애니메이션을 통해 나타나도록 처리했어요. 다시 300px 미만이면 보이지 않도록 했어요.
- 이 버튼에 사용되는 그림자 이펙트가 토큰화 되어 있지 않아 추가했어요.
스토리북 확인 바랍니다!
피그마 상으로는 1280px 내부에 위로 가기 버튼이 있습니다. 1280px 내부로 들여보내려 했는데 `fixed` 되지 않았습니다. 
그래서 `ScrollToTop` 컴포넌트 내부에서 화면 너비를 계산해 리사이징되도록 해보았는데 그렇다면 리사이징이 될 때마다 리렌더링 돼요.
그래서 일단 1280px 외부에 배치 시켜 두었습니다. 디자이너님과 리뷰어님들의 생각이 궁금합니다.
=> [✨ feat] 위로 가기 버튼 추가 (#67)

src/styles/token/spacing.css
- spacing 토큰이 padding, margin, gap 유틸리티 클래스 뿐만아니라 max-w-, max-h- 등의 기본 유틸리티 클래스 값을 오버라이팅하므로 padding, margin, gap 만 적용되도록 수정
- styles/token/spacing.css 수정
- `--spacing-*` tailwindCSS 변수는 많은 유틸클래스의 기본값을 변화시키므로 `--space-*` 컨벤션을 사용, 유틸클래스의 토큰으로 적용되지 않으므로 :root 내에서 정의
- 명확한 유틸클래스 사용하도록 `--padding-*`, `--margin-*`, `--gap-*` tailwindCSS 변수 사용
```css
@import "tailwindcss";
:root {
--space-2xs: 4px;
--space-xs: 8px;
--space-sm: 12px;
--space-md: 16px;
--space-lg: 24px;
--space-xl: 28px;
--space-2xl: 32px;
--space-3xl: 36px;
--space-4xl: 40px;
--space-5xl: 48px;
--space-6xl: 60px;
--space-7xl: 80px;
}
@theme {
--padding-2xs: var(--space-2xs);
--padding-xs: var(--space-xs);
--padding-sm: var(--space-sm);
--padding-md: var(--space-md);
--padding-lg: var(--space-lg); …
```
=> [🔧 fix] spacing 디자인 토큰 제거 및 padding, margin, gap 토큰 분리

lefthook.yml
lefthook에서 prettier에 css 확장자도 검증되도록 추가했어요.
- prettier에 css 확장자를 추가했어요.
=> [🔧 fix] lefthook 검증에서 css 파일도 추가 (#73)

src/app/layout.tsx, src/styles/fonts.css, src/styles/token/font/primitive.css
- 피그마와 font 디자인 토큰 협의 완료하여 font 디자인 토큰 생성
- PR #70 에서 정의한 font 커스텀 클래스의 속성 값을 디자인 토큰으로 적용
- styles/token/font/primitive.css 파일에 font css 전역 변수와 taliwindCSS 유틸클래스를 위한 토큰 정의
- styles/fonts.css 파일 리팩토링
UI 변경 및 클래스명 변경 사항은 없습니다. 
참고 전역 변수로서 사용하기 위해서 `:root {}` 내에서 정의하였고
tailwindCSS 유틸클래스에 적용하기 위해서 `@theme {}` 내에서 다시 정의 했습니다. 
더 좋은 방법이 있으면 코멘트 부탁드립니다. 
그리고 협의된대로 폰트 스타일을 적용할 때는 정의된 커스텀 클래스만 사용하고 그외의 경우는 슬랙으로 상황 공유 부탁드립니다!
=> [♻️ refactor] 폰트 디자인 토큰 정의 및 font 커스텀 클래스 리팩토링

src/components/common/Dropdown.tsx, src/components/common/Icon.tsx, src/components/common/RadioOption.tsx, src/components/common/index.ts, src/components/icons/RadioIcon.tsx, src/components/icons/index.ts, src/stories/Dropdown.stories.tsx, src/stories/RadioOption.stories.tsx, src/styles/globals.css, src/types/iconType.ts
옵션 선택 시 필요한 드롭다운 컴포넌트를 제작했어요.
- `RadioOption` 컴포넌트를 제작하고 스토리북을 작성했어요.
- `Dropdown` 컴포넌트를 제작하고 스토리북을 작성했어요.
- 드롭다운 시 펼쳐지는 항목들은 `RadioOption` 컴포넌트로 만들었어요.
- 옵션 선택 시 라디오 버튼의 활성화 아이콘인 `RadioIcon`을 추가했어요.
- 드롭다운 시 생겨나는 드롭다운 애니메이션 토큰을 추가했어요.
스토리북을 통해 확인할 수 있습니다.
`Option` 컴포넌트를 `check`, `default`, `radio` 타입에 따라 나누어 보려고 했는데 `radio` 옵션밖에 쓰이는 것 같아 일단 우선적인 범위 내에서 하는 것이 맞는 것 같아 `RadioOption`만 제작했어요.
=> [✨ feat] 드롭다운 컴포넌트 구현 (#94)

src/app/(root)/products/[productId]/page.tsx, src/app/(root)/products/[slug]/page.tsx, src/components/common/Dropdown.tsx, src/components/common/button/ScrollToTopButton.tsx, src/components/icons/RadioIcon.tsx, src/components/products/RecommendCarousel.tsx, src/components/products/RecommendProductList.tsx, src/components/products/index.ts, src/components/products/product-detail/ProductActions.tsx, src/components/products/product-detail/ProductDetailItem.tsx, src/components/products/product-detail/ProductHeader.tsx, src/components/products/product-detail/ProductOptions.tsx, src/components/products/product-detail/ProductPrice.tsx, src/components/products/product-detail/ProductQuantity.tsx, src/lib/msw/handlers/index.ts, src/lib/msw/handlers/productsHandlers.ts, src/mocks/products.ts, src/services/fetchProducts.ts, src/stories/product/ProductDetailItem.stories.tsx, src/styles/carousel.css, src/types/productType.ts
상품 상세 페이지 상단에 있는 주요 내용을 담당하는 컴포넌트를 제작했어요.
- 이전 PR 사항에서 `Dropdown` 컴포넌트에 디자인을 수정했어요.
- `RadioIcon`에서 fill 색상을 토큰에 정의된 색상으로 수정했어요.
- `Dropdown` 컴포넌트에서 라벨이 두 줄 이상일 경우 오버플로우 처리했어요.
- 목데이터에 상품에 대한 옵션 정보와 최대 구매 수량을 추가했어요.
- `Product` 타입에 `옵션`과 `최대 구매 수량`을 추가했어요.
- 핸들러와 서비스함수를 임의로 만들어 테스트했어요.
- 추천 상품 캐러셀에서의 arrow 버튼과 플로팅 버튼의 `z-index`를 수정/추가 했어요.
- 상품 상세에 대한 아이템을 제작하고 스토리북을 작성했어요.
스토리북을 통해 확인 바랍니다!
위처럼 `pre-commit`시에 오류가 발생했어요. 
```yaml
pre-commit:
parallel: true
commands:
debug:
run: echo "Running pre-commit hooks"
eslint:
glob: '**/*.{js,ts,jsx,tsx}'
run: pnpm exec eslint "{staged_files}" --fix && echo "ESLint ran on {staged_files}"
stage_fixed: true
prettier:
glob: '**/*.{js,ts,jsx,tsx,json,yaml,md,css}'
run: pnpm exec prettier --write "{staged_files}"
stage_fixed: true
commit-msg:
commands: …
```
=> [✨ feat] 상품 상세 페이지 상단 주요 내용 담당 컴포넌트 제작 (#100)

package.json, pnpm-lock.yaml, src/lib/axios/index.ts, src/mocks/auth.ts, src/server-actions/auth/signinAction.ts, src/services/index.ts, src/services/tokenService.ts
- msw의 임시 로그인 api를 이용해서 로그인 성공 시 반환받은 access_token, refresh_token이 쿠키에 저장되도록 했어요
- axios interceptor를 이용해서 access_token이 있는 경우 모든 api 요청의 header에 Authorization을 실어주도록 했어요
- axios interceptor를 이용해서 access_token 만료 이후의 api 요청 시 refresh_token으로 access_token이 갱신되도록 했어요
서버 사이드 api 요청의 경우에만 interceptor가 요청을 가로채요! 정상적인 의도로 동작되도록 하기 위해서 반드시 클라이언트 사이드에서의 직접적인 api 호출은 하지말아주세요!
=> [✨ feat] JWT 관리 기능 구현

.storybook/main.ts, package.json, pnpm-lock.yaml
클라이언트 환경에서 실행되는 스토리북에 서버 로직이 포함되어있어 에러가 발생해요
- `null-loader` 설치
- webpack 설정을 수정하여 서버 로직이 존재하는 파일(`tokenService`)을 `null-loader`로 대체
- 스토리북 실행시에만 서버 로직이 존재하는 파일(`tokenService`)을 `null-loader`로 대체하도록 webpack 설정을 수정했어요
=> [🐞 hotfix] 클라이언트 환경에서 실행되는 스토리북에 서버 로직이 포함되지 않도록 변경

src/app/(root)/page.tsx, src/queries/productsQueries.ts, src/utils/hydration.ts
- hydration 을 진행하고 dehydration한 데이터 값을 반환하는 유틸 함수 `getDehydratedState`의 인자 쿼리옵션 타입 에러를 해결했어요
- 현재 타입 에러 외에도 고정된 쿼리 옵션의 타입 지정으로 쿼리옵션을 추가할 경우 유틸함수의 타입을 계속 수정해야하는 불편함이 있으므로 tanstack query에서 정의하는 `queryOptions()` 메서드가 반환하는 타입으로 지정했어요.
- 자세한 타입 에러 내용은 #137 이슈에서 확인해주세요!
- `getDehydratedState` 함수의 파라미터 queryOptions의 타입을 tanstack query에서 정의하는  QueryOptions 인터페이스와 제너릭을 활용했어요.
```typescript
import { dehydrate } from '@tanstack/react-query';
import { QueryKey, DehydratedState } from '@tanstack/query-core';
import { QueryObserverOptions } from '@tanstack/react-query';
import { getQueryClient } from '@/lib/tanstack';
export const getDehydratedState = async <
TQueryFnData = unknown,
TError = Error,
TData = TQueryFnData,
TQueryKey extends QueryKey = QueryKey,
>(
// QueryOptions 인터페이스를 사용하여 TanStack …
```
=> [🔧 fix] 유틸 함수 getDehydratedState의 파리미터 queryOptions 타입이슈 해결과 유연성 확장

src/types/index.ts, src/types/ordersType.ts, src/types/paymentsType.ts
- orders와 payments의 API Schema, 타입 정의 ([swagger](https://tutti-server-web-hqbha7bpbxfhcsa8.koreacentral-01.azurewebsites.net/swagger-ui/index.html#/Orders/getOrderPage))
- 장바구니와 상품 상세 페이지 의 버튼에서도 사용
- ordersType.ts, paymentsType.ts 파일추가와 types/index.ts 파일 추가 
**변수명 정의**
-  `orderProductItems`: 주문/결제 페이지에서 결제하기 위한 상품에 대한 리스트
- `orderHistoryList`: 주문 내역 페이지에서 모든 주문 항목에 대한 정보를 보여주는 전체 리스트
- `orderItems`: 주문번호 기준으로 묶인 항목 리스트 
**참고**
백엔드의 경우 : 결제하기 위한 상품에 대한 리스트, 주문번호 기준으로 묶인 항목 리스트 두 경우 모두 `orderItems` 변수 사용
-  `orderItems`: 주문/결제 페이지에서 결제하기 위한 상품에 대한 리스트
- `orders`: 주문 내역 페이지에서 모든 주문 항목에 대한 정보를 보여주는 전체 리스트
- `orderItems`: 주문번호 기준으로 묶인 항목 리스트
=> [✨ feat] orders와 payments의 API Schema, 타입 정의

src/components/cart/CartItem.tsx, src/components/products/product-detail/ProductPrice.tsx, src/hooks/common/useCart.ts, src/services/cartService.ts
비회원/회원에 따라 장바구니 삭제 로직을 추가했어요.
- 비회원/회원에 따른 장바구니 삭제 서비스 함수를 만들고 적용했어요.
- 상품 상세 가격 정보에서 세일 전 가격을 수량이 오르고 내림에 따라 동시에 렌더링 되도록 했어요.
=> [✨ feat] 비회원/회원에 따른 장바구니 삭제 로직 추가 (#147)

src/app/(root)/checkout/page.tsx, src/components/orders-payments/OrderProductList/OrderProductList.tsx, src/components/orders-payments/OrderProductList/OrderProductListGroup.tsx, src/components/orders-payments/OrderProductList/ProductAmoutInfo.tsx, src/components/orders-payments/OrderProductList/ProductOptionInfo.tsx, src/components/orders-payments/OrderProductList/index.ts, src/components/orders-payments/index.ts, src/stories/orders/OrderProductListGroup.stories.tsx, src/types/ordersType.ts, src/utils/dataTransformUtils.ts, src/utils/index.ts
- 도착일 날짜별로 그룹화 되도록 상품 리스트 구조 변경  
- 그룹화 리스트 컴포넌트 추가 생성 
- orderItems의 데이터를 도착일 별 그룹화하는 유틸함수 생성
- order 관련 컴포넌트 스토리북 추가
- 첫번째 항목의 padding-top의 값을 0으로 만들려 했으나 모든 리스트의 padding-top이 0으로 적용된 이슈 수정
- 날짜별 그룹화 UI 추가
=> [✨ feat] 결제할 상품 리스트 도착예상일 별 그룹화 리스팅과 order 관련 스토리북 컴포넌트 추가

src/components/common/button/Button.tsx, src/components/reviews/create-review/CreateReviewButtonBox.tsx, src/components/reviews/create-review/ReviewContent.tsx, src/components/reviews/product-review/ReviewBadge.tsx, src/components/reviews/product-review/ReviewItem.tsx, src/components/reviews/product-review/ReviewLikeButton.tsx, src/constants/endpoints.ts, src/server-actions/index.ts, src/server-actions/review/reviewLikeAction.ts, src/server-actions/review/sentimentFeedbackAction.ts, src/services/reviewService.ts
- 감성 분석 피드백을 위한 UI 및 기능 구현
- 리뷰 등록 시 감성 분석 api를 호출하여 백엔드에서 해당 값을 참조할 수 있도록 구현
- 버튼 컴포넌트의 variant 중 tertiaryOutline에 인터렉션이 전혀 없어 ux 향상을 위한 tertiaryOutlineInteraction 추가
- startTransition으로 useOptimistic의 낙관적 업데이트 처리 방식 개선
=> [✨ feat] 리뷰 감성분석 기능 추가

src/app/(root)/products/[productId]/page.tsx, src/components/products/index.ts, src/components/products/product-detail/ProductDetailInfo.tsx, src/utils/format.ts
상품 상세 페이지에 상세 정보에서 테이블과 이미지를 추가했어요.
- 상품 상세 테이블을 추가했어요. 상품에 대해 정보가 다양하지 않아서 일부는 하드코딩해놨어요.
- 상품 상세 이미지 필드가 따로 주어지지 않아서 썸네일 이미지 url로 이미지를 넣어놨어요.
=> [✨ feat] 상품 상세 페이지에 상품 정보 테이블 및 이미지 추가 (#197)

package.json, pnpm-lock.yaml, src/components/category/ClientCategoryProductList.tsx, src/components/products/ClientProductList.tsx, src/constants/products.ts, src/hooks/common/index.ts, src/hooks/common/useProductListVirtualizer.ts
현재는 전체 상품 목록이 모두 DOM에 렌더링되고 있어서 LCP가 엄청 길어요. 보이지 않는 영역의 상품들까지 모두 렌더링되고 있어서 불필요한 리소스를 사용하고 있어요.
화면에 보이는 상품만 DOM에 렌더링하고 스크롤 시 필요한 요소만 동적으로 추가하고 제거돼요.
목록 가상화를 적용해서 LCP를 줄여 최적화를 했어요.
- `tanstack/react-virtual`을 사용했어요.
- 상품 목록과 카테고리 상품 목록에서 공통적으로 쓰여 훅으로 따로 제작했어요.
- 반응형에 대응하기 위해 크기 별로 `gap`과 `size`를 지정해줬어요.
- 카테고리 상품 리스트와 모든 상품 리스트에 가상화 훅을 적용했어요.
inline css와 같이 작업했는데 이는 동적 값을 처리하기 위해서에요. 
가상화는 픽셀 단위의 정확한 위치 계산을 해야 하고 tailwindcss로 작성하면 우선순위가 상대적으로 높은 인라인 스타일에 덮어씌워질 수 있어요.
=> [✨ feat] 상품 리스트에 목록 가상화 적용 (#194)

src/services/cartService.ts
비회원일 경우에는 장바구니에 담기는 상품 개수를 제한했어요.
로컬스토리지에 저장하다 보니 `productId`에 일치하는 api를 여러 번 요청할 경우가 발생할 수 있어 최소한의 개수로 제한했어요.
- 비회원일 경우 장바구니에 담기는 상품 개수 10개로 제한
=> [♻️ refactor] 비회원일 경우 장바구니에 담기는 상품 개수 제한 (#201)

src/components/cart/CartInfo.tsx, src/stories/cart/CartInfo.stories.tsx
비회원일 경우 결제 페이지로 이동하지 못하게 막았아요.
- 로그인 여부에 따라 결제 페이지 이동 컨트롤
=> [♻️ refactor] 비회원일 경우 결제 페이지로 이동하지 못하게 막기 (#204)

src/app/(root)/faqs/page.tsx, src/components/cart/CartInfo.tsx, src/components/faqs/FaqAccordion.tsx, src/components/faqs/FaqAccordionAnswer.tsx
일부 컴포넌트에서의 스타일링을 수정했어요.
- faq 페이지에서의 스타일을 일부 수정했어요. (화면 너비에 맞게 및 패딩 값 수정)
- faq 아이템을 토글링할 때 존재하지 않는 페이지로 가는 오류를 수정했어요.
- 장바구니 페이지에서 장바구니가 길어지면 가격 정보를 보려고 다시 올려야 해서 `sticky`되도록 스타일을 수정했어요.
https://github.com/user-attachments/assets/16a041a0-a5ae-4e70-9685-d1810e34eca9
=> [✨ design] 일부 컴포넌트에서의 스타일 수정 (#210)

src/app/(root)/products/[productId]/page.tsx, src/lib/axios.ts, src/services/productService.ts
동적 라우트를 가진 상품 상세 페이지를 빌드 타임에서 미리 정적 페이지를 생성하도록 했어요.
- 기존 `axiosInstance`에는 `getAccessToken()`에서 `cookies()`를 request scope 내에서 작동을 해요. 
- `generateStaticParams`는 빌드 시간에 실행돼서 request scope가 없어서 접근할 수 없었어요.
- 그래서 정적 `staticAxios`를 만들었어요.
- 상품 상세 페이지에 SSG를 위한 `generateStaticParams`를 추가했어요.
[Next.js generateStaticParams 트러블슈팅: 성능 최적화를 위한 정적 페이지 생성](https://www.notion.so/heymeworld/Next-js-generateStaticParams-1c844a7e7ac580ccaa27ff25ad84506d)을 참고해주세요!
=> [✨ feat] 동적 라우트를 가진 상품 상세 페이지를 SSG (#236)

src/app/(root)/my/orders/[orderId]/page.tsx, src/app/(root)/my/orders/page.tsx, src/components/common/Badge.tsx, src/components/orders-payments/OrderHistoryList/OrderDetailClientWrapper.tsx, src/components/orders-payments/OrderHistoryList/OrderHistoryClientWrapper.tsx, src/components/orders-payments/OrderHistoryList/OrderHistoryList.tsx, src/components/orders-payments/OrderHistoryList/OrderHistoryListGroup.tsx, src/components/orders-payments/OrderHistoryList/OrderHistoryListGroupHeader.tsx, src/components/orders-payments/OrderHistoryList/OrdersActions.tsx, src/components/orders-payments/OrderHistoryList/OrdersExtraActions.tsx, src/components/orders-payments/OrderHistoryList/index.ts, src/components/orders-payments/OrderStatusBadge.tsx, src/components/orders-payments/ProductAmoutInfo.tsx, src/hooks/index.ts, src/hooks/queries/index.ts, src/hooks/queries/useRefundMutation.ts, src/types/ordersType.ts
- 주문을 취소할 경우 환불 api를 요청하는 서비스함수가 호출될 때 주문상태(orderStatus) UI가 즉각적으로 바뀌지 않아 tanstack query의 mutation을 사용했습니다. 
- 주문 내역/주문 상세 페이지에서 주문 취소 또는 전체 주문 취소 클릭 시 환불 mutation을 활용한 api 호출과  즉각적인 UI 상태 변화
- 디테일한 그리드 정렬 또는 패딩 값 수정
- 주문 취소 시 상태 UI 적용
- 공통 뱃지 컴포넌트에서 파생된 orderStatusBadge 컴포넌트 완성
- 주문 내역
=> [✨ feat] 주문 내역/상세 쿼리옵션으로 일관된 데이터와 UI 관리

src/components/common/Toast.tsx, src/components/reviews/product-review/ProductReview.tsx, src/components/reviews/product-review/ReviewItem.tsx, src/components/reviews/product-review/ReviewLikeButton.tsx, src/utils/toast.tsx
- 비회원 리뷰 좋아요 시 토스트로 로그인 해야함을 알리고 로그인 페이지로 링크 제공
- 즉시 로그인 페이지로 리다이렉션되지는 않아요!
- Toast 컴포넌트에 linkInfo를 추가했어요
- linkInfo의 경우 message props로 Link 컴포넌트를 받기 위해서 ReactNode 타입을 추가했어요
=> [✨ feat] 비회원 리뷰 좋아요 시 토스트로 알림

src/components/cart/CartInfo.tsx, src/components/products/product-detail/ProductActions.tsx
상품 상세 페이지에서 비회원일 때도 결제가 되도록 되어 있는데 회원만 가능하도록 분기 처리를 해줬어요.
- 비회원일 경우 결제 안되도록 막기
=> [🔧 fix] 상품 상세 페이지에서 상품 구매할 때 회원 여부 판별 (#260)

src/app/(root)/my/orders/page.tsx, src/components/orders-payments/OrderHistoryList/AllCancelButton.tsx, src/components/orders-payments/OrderHistoryList/OrderDetailClientWrapper.tsx, src/components/orders-payments/OrderHistoryList/OrderGroupHeader.tsx, src/components/orders-payments/OrderHistoryList/OrderHistoryClientWrapper.tsx, src/components/orders-payments/OrderHistoryList/OrderHistoryList.tsx, src/components/orders-payments/OrderHistoryList/OrderHistoryListGroup.tsx, src/components/orders-payments/OrderHistoryList/OrderIdHeading.tsx, src/components/orders-payments/OrderHistoryList/OrdersActions.tsx, src/components/orders-payments/OrderHistoryList/OrdersExtraActions.tsx, src/components/orders-payments/PaymentMethodSelector.tsx, src/hooks/queries/useRefundMutation.ts, src/mocks/orders.ts, src/queries/ordersQueries.ts, src/services/ordersService.ts, src/types/ordersType.ts, src/types/paymentsType.ts, src/utils/dataTransformUtils.ts
- 주문번호이자 토스페이먼츠 결제 key 필드명 `orderNumber` 에서 `orderSheetNo` 로 변경되어 토스페이먼츠 기능이 동작하지 않는 이슈가 있어요
-  `orderNumber` 속성명을 `orderSheetNo`으로 모두 바꿨어요
- `/orders`, `/orders/{orderId}` 의 스키마 타입을 [스웨거](https://tutti-server-web-hqbha7bpbxfhcsa8.koreacentral-01.azurewebsites.net/swagger-ui/index.html#/Orders/getOrders) 기준으로 수정했어요
=> [🐞 hotfix] 주문결제 api 스키마 변경 반영

src/app/(root)/cart/page.tsx, src/app/(root)/checkout/page.tsx, src/components/cart/CartHeader.tsx, src/components/cart/CartInfo.tsx, src/components/cart/index.ts, src/components/common/PageContentHeader.tsx, src/components/common/index.ts, src/components/mypage/MypageHeader.tsx, src/components/orders-payments/CheckoutHeader.tsx, src/stories/common/PageContentHeader.stories.tsx, src/stories/common/PageTitle.stories.tsx
- 장바구니 페이지, 주문결제 페이지, 마이페이지 헤더에 중복되는 스타일을 컴포넌트화해서 하나로 관리하도록 PageContentHeader 컴포넌트로 리팩토링했어요
- PageTitle과 PageContentHeader 컴포넌트의 스토리를 추가했어요
- 클라이언트 컴포넌트에 위치한 CartHeader 컴포넌트를 서버컴포넌트(page)로 꺼냈어요
- PageContentHeader 컴포넌트를 만들어서 재사용했어요
- 스토리를 추가했어요
- 스토리북에서 레이아웃이 찌그러져 있는 부분 이슈 생성해서 수정 예정이에요
- 브레드크럼을 URL 경로에 따라 자동으로 적용되도록 수정할 예정이에요
=> [♻️ refactor] 중복되는 페이지 헤더 스타일 컴포넌트로 재사용 가능하도록 처리 및 스토리북 추가

src/stories/cart/CartInfo.stories.tsx, src/stories/orders/OrderProductListGroup.stories.tsx, src/stories/pages/auth/ResetPasswordPage.stories.tsx, src/stories/pages/auth/SigninPage.stories.tsx, src/stories/product/ProductDetailItem.stories.tsx, src/stories/product/ProductList.stories.tsx, src/stories/product/RecommendProductList.stories.tsx
- 스토리에서 layout: 'centered' 로 설정되어 레이아웃이 찌그러진 UI가 풀 스크린으로 보이도록 layout: 'fullscreen' 으로 수정했어요.
- decorators 에서 레이아웃 div 요소 width 값을 현재 사이트 설정 기준으로 통일했어요.
- 스토리 들의 레이아웃을 실제 UI 화면에 맞춰서 수정했어요.
```tsx
// MainLayout
<Header isLogin={isLogin} />
<div className="layout-max-width relative w-full flex-1">
<main className="px-container pt-md pb-7xl md:mt-header-height mt-header-heightMobile md:pb-[100px]">
{children}
</main>
</div>
<Footer />
``` 
```tsx
// Story
const meta: Meta<typeof ProductListMock> = {
title: 'Product/ProductList',
component: ProductListMock,
parameters: {
layout: 'fullscreen',
},
decorators: [
Story => (
<div className="layout-max-width m-auto">
<main className="px-container py-md">
<Story />
</main>
</div>
),
],
};
``` 
- auth 는 페이지 화면 기준 맞췄어요.
```tsx
// auth Story
const meta …
```
=> [⚙️ chore] 스토리북에서 레이아웃이 맞지 않는 스토리 UI 일괄 수정

src/components/cart/CartItemHeader.tsx, src/components/cart/CartItemImage.tsx, src/components/orders-payments/OrderHistoryList/OrderHistoryList.tsx, src/components/orders-payments/OrderHistoryList/OrdersExtraActions.tsx, src/components/products/ProductItem.tsx, src/components/products/RecommendProductItem.tsx, src/components/products/product-detail/ProductActions.tsx, src/constants/paths.ts, src/hooks/common/index.ts, src/hooks/common/useAddCart.ts, src/stories/orders/OrderProductListGroup.stories.tsx, src/types/ordersType.ts
`/orders`, `/orders/{orderId}` 응답 값에 `productId`, `orderId`가 추가되어 기존에 구현하지 못한 기능들을 구현했어요
- 주문 리스트 항목 별 상품 마다 상품 상세 페이지 연결
- 주문 리스트 항목 별 상품 리뷰 작성 시 `productId` 추가 전달
- 주문 리스트 항목 별 상품 장바구니 추가 버튼 추가 및 훅 생성
- 상품상세 페이지 링크를 연결하면서 상세페이지 링크를 상수화하여 리팩토링 했어요
- 리뷰 작성 시 전달하는 패스파라미터에 `productId`를 추가했어요
- 주문 내역, 상세 페이지에서 확인하는 상품들을 바로 추가 가능하도록 장바구니 당기 기능을 추가했어요. 여기서 상세페이지의 장바구니 담기 함수 코드 중복이 생겨서 장바구니 담는 기능을 하는 useAddCart 커스텀훅을 만들었어요. 
- 주문 내역에서 장바구니를 추가할 때 수량을 주문했던 그대로 담아야하는지 UX적으로 고민하다가 수량은 1개만 추가하고 장바구니에서 수량을 조절하는 유저플로우를 고려했어요. 어떤게 더 사용자의 경험이 좋을 수 있을까요?
=> [✨ feat] 주문내역, 주문상세 페이지의 주문 리스트 상세페이지 연결, 리뷰작성시 productId 전달, 장바구니 추가 기능 추가

src/app/(root)/products/page.tsx, src/app/api/products/search-list/route.ts, src/components/index.ts, src/components/layout/header/Header.tsx, src/components/layout/header/SearchInput.tsx, src/components/search/ClientSearchResultList.tsx, src/components/search/SearchResultList.tsx, src/components/search/index.ts, src/constants/endpoints.ts, src/constants/products.ts, src/queries/index.ts, src/queries/searchQueries.ts, src/services/productService.ts
상품 검색 api를 연동하고 검색 결과 페이지를 구현했어요.
- 상품 검색 api 연동
- 무한스크롤의 검색 결과 페이지 구현
모바일 환경에서의 검색창 스타일을 추가했어요.
https://github.com/user-attachments/assets/111247a5-a78a-4a20-acd0-897abbc22992
=> [✨ feat] 상품 검색 api 연동 및 페이지 구현 (#312)
