tutti-tutti/tutti-client

.github/auto_assign.yml, .github/workflows/action.yml
PR 시 assignee와 reviewer를 자동으로 지정하기 위해 workflow를 추가해요.
- `auto_assign.yml` 생성
- workflow를 위한 파일 작성
=> [⚙️ chore] auto reviewer를 위한 workflow 추가 (#3)

pnpm-lock.yaml
- axios 패키지 설치로 인한 의존성 업데이트
- pnpm-lock.yaml에 axios 의존성을 추가했어요
=> [🔧 fix] axios 패키지 설치로 인한 의존성 업데이트

postcss.config.mjs
로컬 빌드 시에 발생하지 않는 오류가 vercel에서 발견되는 버그가 발생했어요.
- 버그 수정을 위한 `postcss.config.mjs` 파일을 수정했어요.
[[Next.js 15] CSS Minification fails with "Unclosed block" error during production build](https://github.com/vercel/next.js/issues/75817)
동일한 문제를 겪고 있는 이슈를 확인했어요. 테스트 해보겠습니다!
=> [🐞 hotfix] 로컬 빌드 시 발생하지 않는 오류가 vercel에서 발견되는 버그 발생 (#32)

src/lib/axios/index.ts
- axios instance 구현
- ~API version을 중앙 관리 가능하도록 설계~
- 각 API의 version이 따로 변경되는 경우는 현재 프로젝트에서 없을 거 같아 해당 작업은 포함하지 않았어요
- 서버/클라이언트 사이드를 분기하여 API baseURL을 할당하도록 설계
추후 intercepter를 추가할 예정이에요
=> [✨ feat] Axios instance 구현

postcss.config.mjs, src/lib/axios/index.ts
=> [⚙️ chore] main 브랜치로 머지 시 액션 실행 테스트4 (#37)

src/styles/token/colors/semantic.css
- #50 코멘트 중 누락된 변수를 사용하는 이슈를 확인하여 수정
- styles/token/colors/semantic.css 파일 수정  
=> [✨ design] 중복 변수명을 사용하는 디자인 토큰 수정

src/components/common/Input.tsx, src/components/common/index.ts, src/stories/Input.stories.ts
=> [✨ feat] 인풋 컴포넌트 구현

src/components/common/button/LogoutButton.tsx, src/components/common/index.ts, src/components/layout/header/TextHeader.tsx
헤더의 구성요소인 TextHeader에 로그아웃 버튼을 추가했어요.
- `ClickTextButton`을 통한 로그아웃 버튼 추가
=> [✨ feat] TextHeader에 로그아웃 버튼 삽입 (#58)

src/components/layout/footer/Footer.tsx, src/styles/token/spacing.css
=> [✨ design] spacing 디자인 토큰 40px 단위 추가

src/styles/token/spacing.css
- 오탈자로 인해 spacing 토큰의 css 속성값이 적용되지 않는 이슈 수정
=> [🔧 fix] 오탈자로 인해 spacing 토큰의 css 속성값이 적용되지 않는 이슈 수정

src/app/page.tsx, src/styles/fonts.css, src/styles/globals.css
- font 디자인 토큰을 정의하려고 하였으나 여러 협의 끝에 피그마의 폰트 토큰이 재정리가 되기 전에 사용자 정의 스타일 클래스 위주로 사용!
- globals.css에 fonts.css 파일 import가 추가됐어요.
- 5가지 폰트 스타일 정의를 사용자 정의 클래스로 만들었어요.
- 자동 완성을 위해 @utility 디렉티브를 사용하는 방법으로 커스텀 클래스를 정의하고 익숙하고 가독성이 좋은 방법1 형태로 적용했어요
-  **방법 1**. 익숙한 기본 CSS 형태와 medea 쿼리 중첩 구조
```css
@import "tailwindcss";
@utility font-style-title {
font-size:  40px;
line-height: 36px;
letter-spacing: 1.5px;
font-weight: 600;
@media (max-width: 768px) {
font-size: 24px;
line-height: 36px;
letter-spacing: -0.2px;
font-weight: 600;
}
}
@utility font-style-heading {
font-size:  24px;
line-height: 36px;
letter-spacing: -0.2px;
font-weight: 600;
@media (max-width: 768px) {
font-size: 20px;
line-height: 32px;
letter-spacing: -0.2px;
font-weight: 600;
}
}
@utility …
```
=> [✨ design] font 디자인 토큰 및 시맨틱 스타일 클래스 설정

src/components/common/Switch.tsx, src/components/common/index.ts, src/stories/Switch.stories.tsx
스위치 컴포넌트를 제작했어요.
- `Switch` 컴포넌트 제작
스토리북으로 확인 바랍니다.
=> [✨ feat] 스위치 컴포넌트 제작 (#96)

src/styles/globals.css, src/styles/token/border.css
- font/primitive.css 파일 내 :root 블록에서 정의한 전역변수가 적용되지 않는 이슈 해결
- border-radius 토큰이 tailwindCSS에서 제대로 적용되지 않는 이슈 해결
- globals.css 에 누락된 font/primitive.css  파일 import 추가
- border-radius 토큰 형태 `--border-radius-*` 형태에서 tailwindCSS 유틸클래스에서 사용하는 `--radius-*` 형태로 수정
=> [🐞 hotfix] 디자인 토큰이 적용되지 않거나 오버라이팅 되는 이슈 수정

src/components/common/Switch.tsx
클라이언트 컴포넌트 인 switch 컴포넌트에서 use client 선언 문 누락으로 인한 이슈 해결
- switch 컴포넌트 내 'use client' 문구 추가
=> [🐞 hotfix] switch 컴포넌트의 'use client' 선언 누락으로 인한 이슈 해결

src/components/common/Dropdown.tsx, src/components/common/Icon.tsx, src/components/common/StepProgressBar.tsx, src/components/common/button/IconButton.tsx, src/components/common/index.ts, src/stories/StepProgressBar.stories.ts
장바구니나 결제 단계 등 단계를 나타내는 프로그레스 바를 제작했어요.
- `StepProgressBar` 컴포넌트를 제작하고 스토리북을 작성했어요.
- `Icon` 컴포넌트에 `iconProps` 프로퍼티를 추가했어요. 아이콘의 크기가 변경될 때 이를 사용해 변경하면 돼요.
- 이전 PR에서 `Dropdown` 컴포넌트의 스타일을 일부 수정했어요. 
스토리북으로 확인바랍니다.
=> [✨ feat] 프로그레스 바 컴포넌트 제작 (#108)

src/components/common/Checkbox.tsx, src/components/common/index.ts, src/stories/Checkbox.stories.ts
자주 사용될 체크박스 컴포넌트를 제작했어요.
- 체크박스 컴포넌트를 제작하고 스토리북을 작성했어요.
스토리북을 통해 확인 바랍니다 !
=> [✨ feat] 체크박스 컴포넌트 제작 (#110)

src/app/layout.tsx, src/constants/endpoints.ts, src/lib/axios/index.ts, src/utils/getMswEndpoint.ts
배포 환경에서도 msw가 동작하도록 변경 및 백엔드 서버 주소를 미리 적용했어요
- `src/app/layout.tsx` 개발환경에서만 실행되던 msw를 모든 환경에서 실행되도록 변경
- `src/app/lib/axios.ts` 서버에서 호출인 경우 할당되는 baseURL에서 api version 제거
- `src/utils/getMswEndpoint.ts` msw가 가로채는 요청 경로의 baseURL에서 api version 제거
=> [✨ feat] 배포 환경에서도 msw가 동작하도록 변경 및 백엔드 서버 주소를 미리 적용

src/app/layout.tsx, src/constants/endpoints.ts, src/lib/axios/index.ts, src/utils/getMswEndpoint.ts
이슈: #130 
- 2차 마일스톤 배포 후 DNS조회 에러로 기존 임시 baseURL로 요청을 보내지 못하는 문제
- 백엔드 서버의 baseURL을 적용해서 해결
- msw가 배포 환경에서도 동작하도록 변경
- 기존 임시 baseURL이 아닌 백엔드 서버의 baseURL로의 요청을 가로채도록 수정
=> [⚙️ chore] 2차 마일스톤 | msw가 배포 환경에서도 동작하도록 변경 및 백엔드 baseURL 적용

src/app/layout.tsx, src/instrumentation.ts
#135 이슈 해결
- next js에서 지원하는 [instrumentation](https://nextjs.org/docs/app/building-your-application/optimizing/instrumentation) 파일의 [register 함수](https://nextjs.org/docs/app/api-reference/file-conventions/instrumentation#register-optional)를 사용
- register 함수는 서버 인스턴스가 시작될 때 한 번만 실행됩니다. 서버가 시작될 때 = 가장 빠른 시점에 msw 실행하면서 최적화
- src/instumentaion.ts 파일 생성 및 register 함수 내 msw 로직 적용
```typescript
export async function register() {
if (process.env.NEXT_RUNTIME === 'nodejs') {
const { server } = await import('./lib/msw/server');
server.listen();
}
}
``` 
- layout.tsx 파일 내 즉시실행함수로 실행되는 msw 로직 삭제
```typescript
(async () => {
const { initMsw } = await import('../lib/msw');
await initMsw();
})();
``` 
**Instumentation** 
- …
=> [🔧 fix] MSW 최초 렌더링 시 500 문제 해결

src/lib/msw/handlers/authHandlers.ts, src/services/authService.ts
api request body의 json 키를 camelCase로 수정
- authHandlers 주석 처리
- api request body의 json 키를 camelCase로 수정
=> [✨ feat] api request body의 json 키를 camelCase로 수정

next.config.ts
- 현재는 mock data 이미지의 도메인만 추가되어 있으면 서버에서 사용하는 이미지 도메인 허용 추가
- 서버에서 사용하는 이미지 url을 next.config 파일에 추가
=> [⚙️ chore] 이미지 외부 도메인 허용 설정 추가

src/app/(root)/page.tsx, src/app/(root)/products/[productId]/page.tsx, src/components/common/button/MoreViewButton.tsx, src/components/products/ClientProductList.tsx, src/components/products/ProductList.tsx, src/components/products/index.ts, src/components/products/product-detail/ClientProductDetail.tsx, src/components/products/product-detail/ProductActions.tsx, src/components/products/skeleton/ProductListSkeleton.tsx, src/constants/endpoints.ts, src/lib/msw/handlers/productsHandlers.ts, src/queries/productsQueries.ts, src/services/cartService.ts, src/services/productService.ts, src/stores/cartStore.ts, src/stores/createCartMocks.ts
상품 도메인에 쿼리를 적용했어요.
- 상품 관련 msw 핸들러를 주석 처리했어요.
- 전체 상품과 상세 상품 조회 쿼리를 추가했어요.
- 상품 조회 엔드포인트를 수정했어요.
PR 올릴 때 빌드 시 오류 있는지 확인해주세요 🙏
=> [✨ feat] 상품 도메인에 쿼리 적용 (#160) 

src/app/api/cart/[cartItemId]/route.ts, src/app/api/cart/route.ts
회원일 경우 장바구니에 추가, 삭제에서 발생했던 오류를 수정했어요. 오류도 있었지만 삭제에 대한 api route를 추가를 안했었네여 ㅎㅎ
- 삭제에 대한 api route 추가
- 장바구니에 추가 api route에서 필요없는 `productId` 로직 제거
=> [🐞 hotfix] 회원일 경우에서 장바구니에서 발생하는 오류 수정 (#166)

.storybook/preview.tsx, src/components/cart/CartInfo.tsx, src/components/cart/CartItemPrice.tsx, src/components/cart/CartPaymentInfo.tsx, src/components/products/ProductItem.tsx, src/components/products/RecommendProductItem.tsx, src/components/products/product-detail/ProductDetailItem.tsx, src/components/products/product-detail/ProductPrice.tsx, src/services/cartService.ts, src/stores/cartStore.ts, src/stories/product/ProductDetailItem.stories.tsx, src/stories/product/ProductItem.stories.tsx, src/stories/product/ProductList.stories.tsx, src/stories/product/RecommendProductItem.stories.tsx, src/stories/product/RecommendProductList.stories.tsx, src/types/productType.ts, src/utils/calculate.ts
변경된 상품 데이터 구조에 따라 가격 정보 리팩토링을 했어요.
- 서버 데이터 구조에 맞게 수정했어요.
- 데이터 구조가 수정되어서 가격 정보쪽 리팩토링을 했어요.
- 상품 데이터 타입이 변경되면서 스토리북 인자를 수정했어요.
=> [♻️ refactor] 상품 데이터 구조에 맞춰 가격 정보 수정 (#176)

src/app/(root)/products/[productId]/page.tsx, src/components/common/Icon.tsx, src/components/icons/ThinkingFaceIcon.tsx, src/components/icons/index.ts, src/components/products/product-detail/ClientProductDetail.tsx, src/components/products/product-detail/ProductDetailItem.tsx, src/components/products/product-detail/ProductHeader.tsx, src/components/reviews/product-review/AverageReview.tsx, src/components/reviews/product-review/ReviewBadge.tsx, src/components/reviews/product-review/ReviewItem.tsx, src/components/reviews/product-review/ReviewLikeButton.tsx, src/services/reviewService.ts, src/types/iconType.ts, src/types/productType.ts, src/types/reviewType.ts
=> [✨ design] 상품별 리뷰 모바일 디자인 추가

src/queries/ordersQueries.ts
- orders 쿼리 옵션 파라미터 type error 수정
=> [🐞 hotfix] 배포 빌드 에러 수정

src/components/products/RecommendProductList.tsx
메인페이지의 경우 카테고리명이 존재하지 않아 추천 상품 메시지를 변경했어요.
- 추천 상품 메시지 조건부 렌더링
=> [♻️ refactor] 카테고리명이 없을 경우의 추천 상품 메시지 변경 (#216)

src/components/common/Logo.tsx, src/components/common/header/NavIcon.tsx, src/components/common/header/SearchInput.tsx, src/components/layout/header/Header.tsx, src/components/layout/header/HeaderNavigation.tsx, src/stories/NavIcon.stories.tsx
=> [✨ design] 헤더 디자인 수정에 따라 스타일 수정 (#227)

src/components/auth/ResetPwForm.tsx, src/components/auth/SigninForm.tsx, src/components/auth/SignupForm.tsx, src/constants/auth.ts, src/schemas/auth/authSchema.ts, src/server-actions/auth/requestVerificationCodeAction.ts, src/server-actions/auth/resetPwAction.ts, src/server-actions/auth/signinAction.ts, src/server-actions/auth/signupAction.ts, src/server-actions/auth/verifyCodeAction.ts, src/services/authService.ts, src/types/authType.ts
- 로그인, 회원가입, 비밀번호 재설정 시 서버 에러를 UI에 표시하도록 구현
- 비밀번호 필드에 대한 서버 유효성 검증에 맞춰 클라이언트 정규식 업데이트
=> [✨ feat] auth 서버 에러 핸들링

src/components/auth/ResetPwForm.tsx, src/components/auth/SigninForm.tsx, src/components/auth/SignupForm.tsx, src/server-actions/auth/resetPwAction.ts, src/server-actions/auth/signinAction.ts, src/server-actions/auth/signupAction.ts
- 로그인 / 회원가입 / 비밀번호 재설정 이후 메인 혹은 로그인 페이지로 리다이렉팅 되도록 기능 추가
=> [✨ feat] 인증 페이지 리다이렉션

src/components/faqs/CategoryFilterItem.tsx, src/components/faqs/FaqAccordionItemQuestion.tsx, src/components/faqs/SubCategoryFilterItem.tsx, src/components/reviews/product-review/ProductReview.tsx, src/components/reviews/product-review/ReviewItem.tsx, src/components/reviews/product-review/ReviewList.tsx, src/components/reviews/product-review/ReviewRatingBar.tsx, src/components/reviews/product-review/ReviewSort.tsx, src/server-actions/review/sentimentFeedbackAction.ts
- 비회원 리뷰 좋아요 시 회원 기능임을 표시, 리뷰 정렬 텍스트 활성화 수정
=> [🔧 fix] 비회원 리뷰 좋아요 시 회원 기능임을 표시, 리뷰 정렬 텍스트 활성화 수정

src/app/(root)/cart/page.tsx, src/app/(root)/products/[productId]/page.tsx
상품 도메인에서 간단한 수정사항을 반영했어요.
- 상품 상세페이지에서 챗봇 영역 제거
- 장바구니 추천 메시지 수정
=> [🔧 fix] 상품 도메인 간단한 수정사항 반영 (#246)

src/app/(root)/my/orders/[orderId]/page.tsx, src/components/orders-payments/OrderHistoryList/OrderDetailListGroupHeader.tsx, src/components/orders-payments/OrderHistoryList/OrderHistoryList.tsx, src/components/orders-payments/OrderHistoryList/OrderIdHeading.tsx, src/components/orders-payments/OrderHistoryList/OrdersExtraActions.tsx, src/components/orders-payments/OrderProductList/OrderProductList.tsx, src/utils/dataTransformUtils.ts
- 도착 예정일자 확인
- 주문내역 리스트 sort 확인
- 주문번호에 orderId 값이 아닌 orderNumber 적용
- [피드백 슬랙 스레드 링크](https://2-pgl9096.slack.com/archives/C08BSP71DGE/p1743563525499449)
=> [🔧 fix] 주문/결제 관련 수정사항 반영

src/components/products/product-detail/ProductDetailItem.tsx, src/components/products/product-detail/ProductHeader.tsx, src/components/products/product-detail/ProductOptions.tsx
상품 상세 옵션이 없는 경우 보더가 딱 붙는 현상 수정
=> [💅 design] 상품 상세 옵션이 없는 경우 보더가 딱 붙는 현상 수정

src/lib/nextAuth.ts, src/services/tokenService.ts
=> [🐞 hotfix] 소셜로그인 성공 시 jwt가 쿠키에 저장되지 않는 문제 해결

src/components/reviews/create-review/ReviewProductInfo.tsx, src/services/reviewService.ts
=> [🔧 fix] 리뷰 작성 시 상품 데이터를 페칭하도록 수정

src/app/(root)/my/orders/page.tsx, src/components/common/NoData.tsx, src/components/common/index.ts
=> [✨ design] No Data UI 컴포넌트 생성

README.md
- 리드미 파일에 서비스소개와 개발환경 설치 등의 내용을 추가했습니다. 
=> docs: 리드미 파일에 서비스 소개와 개발환경 안내 추가 (#269)

src/components/cart/CartHeader.tsx, src/components/cart/CartInfo.tsx, src/components/cart/CartItem.tsx, src/components/cart/CartItemPrice.tsx, src/components/cart/CartItemQuantity.tsx, src/components/cart/CartList.tsx, src/components/cart/CartPaymentInfo.tsx, src/components/category/ProductCategory.tsx, src/components/common/Dropdown.tsx, src/components/common/button/MoreViewButton.tsx, src/components/products/ProductItem.tsx, src/components/products/RecommendCarousel.tsx, src/components/products/RecommendProductItem.tsx, src/components/products/RecommendProductList.tsx, src/components/products/product-detail/ProductActions.tsx, src/components/products/product-detail/ProductDetailInfo.tsx, src/components/products/product-detail/ProductHeader.tsx, src/components/products/product-detail/ProductOptions.tsx, src/components/products/product-detail/ProductPrice.tsx, src/components/products/product-detail/ProductQuantity.tsx, src/constants/cart.ts, src/constants/index.ts, src/constants/products.ts, src/hooks/common/useCart.ts, src/services/cartService.ts
상품과 장바구니 도메인에서 한글로 하드코딩된 것을 상수로 모듈화했어요.
- 상품 도메인 상수 모듈화
- 장바구니 도메인 상수 모듈화
=> [♻️ refactor] 상품, 장바구니 도메인에서 한글로 하드코딩된 것 상수로 모듈화 (#273)

src/app/not-found.tsx, src/components/common/Badge.tsx, src/components/common/button/Button.tsx, src/components/orders-payments/OrderStatusBadge.tsx, src/constants/orders.ts, src/stories/common/Badge.stories.tsx, src/stories/common/button/Button.stories.ts, src/stories/common/button/ClickTextButton.stories.ts, src/stories/orders/OrderStatusBadge.stories.tsx, src/types/badgeType.ts
- 아톰 컴포넌트에서 누란된 스토리북 생성
- Button 컴포넌트 내 Link 요소 사용 가능하도록 수정 : 요소와 요소 분리를 위해
- Badge, OrderStatus 컴포넌트 리팩토링
- Badge 스토리북 생성
- OrderStatus 컴포넌트 스토리북 생성
- Button 컴포넌트 수정
=> [♻️ refactor] Badge, OrderStatus, Button 컴포넌트 리팩토링 및 스토리 생성과 수정

src/components/cart/CartItem.tsx, src/components/cart/CartItemHeader.tsx, src/components/cart/CartItemImage.tsx, src/components/cart/CartItemSkeleton.tsx, src/components/cart/CartList.tsx, src/components/common/NoData.tsx, src/components/products/product-detail/ProductActions.tsx, src/mocks/cart.ts, src/services/cartService.ts, src/stores/createCartMocks.ts, src/types/cartType.ts
회원이 장바구니에 추가 시에 maxQuantity까지 추가되도록 수정했어요.
- 회원이 장바구니에 상품을 추가할 때 `maxQuantity` 까지 추가되도록 수정했어요. 
- 장바구니에서 상품 상세 페이지로 라우팅되도록 수정했어요.
- `NoData` 컴포넌트에서 스타일을 일부 수정했어요.
- 장바구니에 데이터가 없을 경우 `NoData` 컴포넌트로 대체했어요.
BDD 완료 !
=> [♻️ refactor] 회원 장바구니 추가 시 maxQuantity 까지 추가되도록 수정 (#298) 

src/components/cart/CartItem.tsx, src/components/cart/CartItemHeader.tsx, src/components/cart/CartItemImage.tsx, src/mocks/cart.ts, src/services/cartService.ts, src/stores/createCartMocks.ts, src/types/cartType.ts
회원 장바구니의 `productItemName`의 필드명이 수정에 따라 필드명을 동일하게 변경했어요.
- 필드명 변경
=> [♻️ refactor] 장바구니 `productName` 필드명 수정에 따른 코드 수정 (#309)

src/components/checkout/PaymentMethodSelector.tsx, src/components/orders-payments/OrderTableInfoSection.tsx, src/constants/endpoints.ts, src/types/ordersType.ts, src/types/paymentsType.ts
- 주문결제 API 엔드포인트 및 스키마 수정사항 반영
- 주문서 작성 페이지 엔드포인트 수정: /orders/checkout -> orders/ordersheet
- 환불 엔드포인트 중간 경로 수정 : /refund/order/{orderId} → 중간 경로 /refund/orders/{orderId}
- 상세 주소 필드 recipientAddressDetail 추가
- POST /payments 주문/결제 요청 Request DTO
- GET /orders/{orderId} 주문 내역 상세 조회 Response DTO
=> [🔧 fix] 주문결제 API 수정사항 반영
